input_data = open('input.txt','r')
data = input_data.read()
output_data = open('output.txt','w')
data=data.split()
b1 = int(data[0])
q = int(data[1])
n = int(data[2])
S=(b1*(1-q**n))//(1-q)
output_data.write(str(S))
output_data.close()
input_data.close()